#默认配置
spring:
  profiles:
    active: dev

#公共配置

mybatis-plus:
  #  起别名。可省略mybatis的xml文件
  type-aliases-package: com.masaiqi.entity
  mapper-locations: classpath*:mapper/*.xml
#  配置mybatis的sql语句显示在控制台中(将mapper类的日志输出级别为debug)
logging:
  level:
    com:
      masaiqi:
        mapper: debug

---
#开发环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhongzhiplatform?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据连接池
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8090

---
#生产环境
spring:
  profiles: prod

server:
  port: 80
