#默认配置
spring:
  profiles:
    active: dev

#公共配置
mybatis:
  type-aliases-package: com.masaiqi.entity
  mapper-locations: classpath:mapper/*.xml

---
#开发环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhongzhiplatform?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据连接池
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8090

---
#生产环境
spring:
  profiles: prod

server:
  port: 80
